services:
  simplehealth_db:
    image: mongo:7
    container_name: simplehealth_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: simplehealth
      MONGO_INITDB_ROOT_PASSWORD: simplehealth
      MONGO_INITDB_DATABASE: simplehealth_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

volumes:
  mongo_data:
  mongo_config:
  redis_data:
