services:
  simplehealth_db:
    image: mongo:7
    container_name: simplehealth_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: simplehealth
      MONGO_INITDB_ROOT_PASSWORD: simplehealth
      MONGO_INITDB_DATABASE: simplehealth_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/config:/data/configdb


  redis:
    image: redis:7
    container_name: redis_local
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
